Repository Rodrigues-Developers/api-logistica, pull requests merged in 2024-03, with the labels that each got.

#10 feat: updated note type
  models/logisticSchema.js
Labels: back-end

#11 Cruds
  controllers/logisticConnection.js
  controllers/logisticController.js
  controllers/productController.js
  models/logisticSchema.js
  models/productSchema.js
Labels: enhancement, back-end

#13 feat: one more atribute for logistic: 'key', to check if the note has…
  models/logisticSchema.js
Labels: enhancement, front-end
